language: go
go:
  - 1.8
  - 1.9
  - tip
install:
  - mkdir -p $HOME/gopath/src/gopkg.in/gemnasium
  - mv $HOME/gopath/src/github.com/gemnasium/logrus-airbrake-legacy-hook $HOME/gopath/src/gopkg.in/gemnasium/logrus-airbrake-legacy-hook.v1
  - cd $HOME/gopath/src/gopkg.in/gemnasium/logrus-airbrake-legacy-hook.v1
  - go get -t
